language: cpp
git:
  submodules: false
before_install:
    - sudo apt-get update -y
    - sudo apt-get install gcc g++ gfortran make cmake zlib1g-dev python-dateutil python-pyparsing python-numpy python-matplotlib python-pip python-setuptools python-dev -y
    - cmake --version
    - gcc --version
    - g++ --version
    - gfortran --version
    - python --version
script:
  - python setup.py --cxx=g++ --cc=gcc --fc=gfortran --type=debug --cmake-options='-Hprojects/CMake -DENABLE_FORTRAN_API=ON'
  - cd build
  - VERBOSE=1 make
  - ctest -V
notifications:
  recipients:
    - roberto.d.remigio@uit.no
    - luca.frediani@uit.no
  email:
    on_success: change
    on_failure: always
